# Generated by Django 3.2.14 on 2022-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=20)),
                ('bookTitle', models.CharField(max_length=100)),
                ('bookAuthorName', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('bookImage', models.FileField(upload_to='')),
            ],
        ),
    ]
