# Generated by Django 3.2.14 on 2022-08-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=20)),
                ('studentAddress', models.CharField(max_length=100)),
                ('stuEmail', models.EmailField(max_length=254)),
                ('stuPhoneNumber', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='bookImage',
        ),
    ]
